In [56]:
import pandas as pd
import numpy as np

- Ejercicios

¿Qué diferencia hay entre una Serie y un DataFrame?

Serie: unidimencional / con etiquetas 
Dataframe: Bidimencional (filas y coolumnas)

In [57]:
#Crea un array de dos dimensiones con 4 filas y 3 columnas.

array_1= np.random.rand (4,3)
print(array_1)

# se utilizó un ramdom para no insertar datos nosotras

[[0.18185959 0.3675455  0.35434854]
 [0.64341546 0.08203894 0.16981639]
 [0.54917267 0.59009076 0.3545007 ]
 [0.30206986 0.81948999 0.01821344]]


In [58]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_paises =pd.DataFrame(array_1,columns=["España","Francia" , "Italia"])

df_paises.head()

,España,Francia,Italia
0,0.181860,0.367546,0.354349
1,0.643415,0.082039,0.169816
2,0.549173,0.590091,0.354501
3,0.302070,0.819490,0.018213


In [59]:
#Descarga el archivo "medallas" y carga el DataFrame.

df_medallas= pd.read_csv("medallas.csv", index_col=0)

In [60]:
df_medallas

,País,Oro,Plata,Bronce
1,China,1473,994,720
2,Japón,1032,1037,985
3,Corea del Sur,745,663,827
4,Irán,179,181,197
5,Kazajistán,155,158,224
6,India,154,202,315
7,Tailandia,132,175,278
8,Indonesia,112,131,240
9,China Taipéi,99,144,276
10,Corea del Norte,91,120,235


In [61]:
#Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas.loc[df_medallas["País"]=="Tailandia"] 



,País,Oro,Plata,Bronce
7,Tailandia,132,175,278


In [62]:
df_medallas.iloc[6]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [63]:
#Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[(df_medallas["País"]=="China")|(df_medallas["País"]=="Irán")]



,País,Oro,Plata,Bronce
1,China,1473,994,720
4,Irán,179,181,197


In [64]:
China_Iran= df_medallas.loc[(df_medallas["País"]=="China")|(df_medallas["País"]=="Irán")]

In [65]:
#Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
China_Iran.loc[:,["Oro","Plata","Bronce"]]

,Oro,Plata,Bronce
1,1473,994,720
4,179,181,197


In [66]:
#Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón 
# y la última Corea del Norte.
df_medallas.iloc[1::2,:]

,País,Oro,Plata,Bronce
2,Japón,1032,1037,985
4,Irán,179,181,197
6,India,154,202,315
8,Indonesia,112,131,240
10,Corea del Norte,91,120,235


In [67]:
#Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
df_medallas.iloc[1::2,1:4]

,Oro,Plata,Bronce
2,1032,1037,985
4,179,181,197
6,154,202,315
8,112,131,240
10,91,120,235


In [68]:
#¿Qué país consiguió más de 200 medallas de oro?
df_medallas.loc[df_medallas.Oro > 200]

,País,Oro,Plata,Bronce
1,China,1473,994,720
2,Japón,1032,1037,985
3,Corea del Sur,745,663,827


In [69]:
#¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

resultado_1 = df_medallas[(df_medallas["Oro"] > 200) & (df_medallas["Plata"] > 1000)]
print(resultado_1["País"])

2    Japón
Name: País, dtype: str


In [70]:
#¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

resultado_2 = df_medallas[(df_medallas["Oro"] > 200) | (df_medallas["Bronce"] > 700)]
print(resultado_2["País"])

1            China
2            Japón
3    Corea del Sur
Name: País, dtype: str


In [71]:
#Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas["total"] = df_medallas[["Oro", "Plata", "Bronce"]].sum(axis=1)
#axis=1 para sumar por filas
df_medallas ["total"]
#Ordena el DataFrame por la columna "total" de mayor a menor.

1     3187
2     3054
3     2235
4      557
5      537
6      671
7      585
8      483
9      519
10     446
Name: total, dtype: int64

- Momento de trabajar con Series. Contesta a las siguientes preguntas:

Crea dos listas:

In [78]:
#Una que se llame "valores" que tenga 7 números aleatorios.

lista = list(np.random.rand(7))
# lista es un array de una dimensión, por eso se ha convertido a lista para que sea más fácil de leer
lista

[np.float64(0.6754412669330248),
 np.float64(0.37687669203161067),
 np.float64(0.9408127174672142),
 np.float64(0.3454750651868821),
 np.float64(0.5270756023336779),
 np.float64(0.0583517912939282),
 np.float64(0.6829523831703089)]

In [74]:
#Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

indices = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]
#indices es una lista de strings que se ha creado para ser utilizada como índices en el DataFrame
indices

['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

In [76]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices 
# de la Serie.

serie = pd.Series(data=lista, index=indices)
serie

Lunes        0.293294
Martes       0.310684
Miércoles    0.136537
Jueves       0.543782
Viernes      0.509495
Sábado       0.775014
Domingo      0.843804
dtype: float64