In [32]:
import pandas as pd
import numpy as np

- Ejercicios

¿Qué diferencia hay entre una Serie y un DataFrame?

Serie: unidimencional / con etiquetas 
Dataframe: Bidimencional (filas y coolumnas)

In [33]:
#Crea un array de dos dimensiones con 4 filas y 3 columnas.

array_1= np.random.rand (4,3)
print(array_1)

# se utilizó un ramdom para no insertar datos nosotras

[[0.679336   0.17063227 0.01723214]
 [0.37680069 0.46689597 0.32010604]
 [0.08091846 0.72173832 0.90773793]
 [0.81662682 0.15399769 0.8098851 ]]


In [34]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_paises =pd.DataFrame(array_1,columns=["España","Francia" , "Italia"])

df_paises.head()

,España,Francia,Italia
0,0.679336,0.170632,0.017232
1,0.376801,0.466896,0.320106
2,0.080918,0.721738,0.907738
3,0.816627,0.153998,0.809885


In [35]:
#Descarga el archivo "medallas" y carga el DataFrame.

df_medallas= pd.read_csv("medallas.csv", index_col=0)

In [36]:
df_medallas

,País,Oro,Plata,Bronce
1,China,1473,994,720
2,Japón,1032,1037,985
3,Corea del Sur,745,663,827
4,Irán,179,181,197
5,Kazajistán,155,158,224
6,India,154,202,315
7,Tailandia,132,175,278
8,Indonesia,112,131,240
9,China Taipéi,99,144,276
10,Corea del Norte,91,120,235


In [37]:
#Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas.loc[df_medallas["País"]=="Tailandia"] 



,País,Oro,Plata,Bronce
7,Tailandia,132,175,278


In [38]:
df_medallas.iloc[6]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [47]:
#Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[(df_medallas["País"]=="China")|(df_medallas["País"]=="Irán")]



,País,Oro,Plata,Bronce
1,China,1473,994,720
4,Irán,179,181,197


In [60]:
China_Iran= df_medallas.loc[(df_medallas["País"]=="China")|(df_medallas["País"]=="Irán")]

In [66]:
#Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
China_Iran.loc[:,["Oro","Plata","Bronce"]]

,Oro,Plata,Bronce
1,1473,994,720
4,179,181,197


In [87]:
#Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón 
# y la última Corea del Norte.
df_medallas.iloc[1::2,:]

,País,Oro,Plata,Bronce
2,Japón,1032,1037,985
4,Irán,179,181,197
6,India,154,202,315
8,Indonesia,112,131,240
10,Corea del Norte,91,120,235


In [88]:
#Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
df_medallas.iloc[1::2,1:4]

,Oro,Plata,Bronce
2,1032,1037,985
4,179,181,197
6,154,202,315
8,112,131,240
10,91,120,235


In [90]:
#¿Qué país consiguió más de 200 medallas de oro?
df_medallas.loc[df_medallas.Oro > 200]

,País,Oro,Plata,Bronce
1,China,1473,994,720
2,Japón,1032,1037,985
3,Corea del Sur,745,663,827
